import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Layout
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

// Contexts
import { ModalProvider } from "../contexts/ModalContext";
import { ThemeProvider } from "../contexts/ThemeContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jed Delich | Software Engineer",
  description: "Generated by create next app",
  icons: {
    apple: "/favicons/apple-touch-icon.png",
    icon: [
      { url: "/favicons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <ModalProvider>
            <Navbar />
            {children}
            <Footer />
          </ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
